//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 畢業專題.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbtMemberEntities1 : DbContext
    {
        public dbtMemberEntities1()
            : base("name=dbtMemberEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tLogin> tLogin { get; set; }
        public virtual DbSet<tRegister> tRegister { get; set; }
        public virtual DbSet<tLogout> tLogout { get; set; }
        public virtual DbSet<tAdopt> tAdopt { get; set; }
        public virtual DbSet<tContact> tContact { get; set; }
        public virtual DbSet<tDogs> tDogs { get; set; }
        public virtual DbSet<tReserve> tReserve { get; set; }
        public virtual DbSet<tRegisterBackup> tRegisterBackup { get; set; }
    }
}
