//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 畢業專題.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tDogs()
        {
            this.tAdopt = new HashSet<tAdopt>();
        }
    
        public int dogId { get; set; }
        public string dogName { get; set; }
        public string dogBreed { get; set; }
        public string dogSize { get; set; }
        public int dogAge { get; set; }
        public string dogSex { get; set; }
        public string dogNeuter { get; set; }
        public string dogStory { get; set; }
        public string dogImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tAdopt> tAdopt { get; set; }
    }
}
