//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 畢業專題.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRegisterBackup
    {
        public string username { get; set; }
        public int userPhone { get; set; }
        public string userAccount { get; set; }
        public string userPassword { get; set; }
        public string userEmail { get; set; }
        public string tempGuid { get; set; }
        public string emailCheck { get; set; }
        public string userExp { get; set; }
        public string userLog { get; set; }
    }
}
